"""
agents/competitive_agent.py
-----------------------------
Competitive Analysis Agent — aggregates processed brand data into:
  - Per-brand metrics (avg price, avg discount, avg rating, sentiment)
  - Cross-brand rankings and comparisons
  - "Who is winning and why" narrative (generated by GPT-4o-mini)
  - 5 Agent Insights (non-obvious conclusions)
  - Value-for-money scores

Run directly:
    python -m backend.agents.competitive_agent

Input:  backend/data/processed/{brand}_insights.json (one per brand)
Output: backend/data/processed/competitive_summary.json

This is the final "merge" step — it's the file the API serves directly.
"""

import json
import sys
from pathlib import Path
from statistics import mean

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from openai import OpenAI

from backend.config import (
    OPENAI_API_KEY,
    LLM_MODEL,
    TARGET_BRANDS,
    PROCESSED_DIR,
)
from backend.utils.helpers import load_json, save_json, timestamp, value_score


client = OpenAI(api_key=OPENAI_API_KEY)


# ── Metrics computation ────────────────────────────────────────────────────

def compute_brand_metrics(brand_data: dict) -> dict:
    """
    Compute aggregate pricing and rating metrics for a brand from product list.
    Returns a flat dict ready for comparison tables and charts.
    """
    products = brand_data.get("products", [])
    insights = brand_data.get("insights", {})

    # Collect valid (non-None) values for each metric
    sale_prices = [p["sale_price"] for p in products if p.get("sale_price")]
    list_prices = [p["list_price"] for p in products if p.get("list_price")]
    discounts = [p["discount_pct"] for p in products if p.get("discount_pct") is not None]
    ratings = [p["rating"] for p in products if p.get("rating")]
    review_counts = [len(p.get("reviews", [])) for p in products]

    avg_price = round(mean(sale_prices), 0) if sale_prices else 0.0
    avg_list_price = round(mean(list_prices), 0) if list_prices else 0.0
    avg_discount = round(mean(discounts), 1) if discounts else 0.0
    avg_rating = round(mean(ratings), 2) if ratings else 0.0
    total_reviews = sum(review_counts)

    sentiment_score = insights.get("sentiment_score", 0.5)

    # Price band classification (used in overview + comparison)
    if avg_price >= 3500:
        price_band = "Premium"
    elif avg_price >= 1800:
        price_band = "Mid-range"
    else:
        price_band = "Budget"

    return {
        "brand": brand_data["brand"],
        "product_count": len(products),
        "review_count": brand_data.get("review_count", total_reviews),
        "avg_price": avg_price,
        "avg_list_price": avg_list_price,
        "avg_discount_pct": avg_discount,
        "avg_rating": avg_rating,
        "total_reviews": total_reviews,
        "sentiment_score": sentiment_score,
        "sentiment_label": insights.get("sentiment_label", "N/A"),
        "price_band": price_band,
        "positive_themes": insights.get("positive_themes", []),
        "negative_themes": insights.get("negative_themes", []),
        "recurring_praise": insights.get("recurring_praise", []),
        "recurring_complaints": insights.get("recurring_complaints", []),
        "aspect_sentiment": insights.get("aspect_sentiment", {}),
        "one_line_summary": insights.get("one_line_summary", ""),
        "value_score": value_score(sentiment_score, avg_price),
        # Product list for the drilldown view
        "products": products,
    }


def rank_brands(brand_metrics: list[dict]) -> list[dict]:
    """
    Add rank fields to each brand based on key competitive metrics.
    Ranks are 1 = best.
    """
    # Sort copies to determine ranks, then update originals
    by_rating = sorted(brand_metrics, key=lambda x: x["avg_rating"], reverse=True)
    by_sentiment = sorted(brand_metrics, key=lambda x: x["sentiment_score"], reverse=True)
    by_value = sorted(brand_metrics, key=lambda x: x["value_score"], reverse=True)
    by_discount = sorted(brand_metrics, key=lambda x: x["avg_discount_pct"], reverse=True)

    rating_ranks = {b["brand"]: i + 1 for i, b in enumerate(by_rating)}
    sentiment_ranks = {b["brand"]: i + 1 for i, b in enumerate(by_sentiment)}
    value_ranks = {b["brand"]: i + 1 for i, b in enumerate(by_value)}
    discount_ranks = {b["brand"]: i + 1 for i, b in enumerate(by_discount)}

    for b in brand_metrics:
        name = b["brand"]
        b["rank_by_rating"] = rating_ranks[name]
        b["rank_by_sentiment"] = sentiment_ranks[name]
        b["rank_by_value"] = value_ranks[name]
        b["rank_by_discount"] = discount_ranks[name]

    return brand_metrics


# ── LLM-generated competitive narrative ───────────────────────────────────

def build_competitive_summary_prompt(brand_metrics: list[dict]) -> str:
    """
    Build a prompt that gives GPT the full cross-brand picture
    and asks for the "who is winning and why" narrative + 5 agent insights.
    """
    # Compact summary table for the prompt
    summary_lines = []
    for b in brand_metrics:
        summary_lines.append(
            f"- {b['brand']}: avg_price=₹{b['avg_price']}, "
            f"avg_discount={b['avg_discount_pct']}%, "
            f"avg_rating={b['avg_rating']}/5, "
            f"sentiment={b['sentiment_score']:.2f} ({b['sentiment_label']}), "
            f"price_band={b['price_band']}, "
            f"top_complaints={b['recurring_complaints'][:2]}, "
            f"top_praise={b['recurring_praise'][:2]}"
        )
    brands_summary = "\n".join(summary_lines)

    return f"""You are a competitive intelligence analyst for Amazon India luggage brands.
Here is the aggregated data across {len(brand_metrics)} brands:

{brands_summary}

Return ONLY this JSON (no markdown, no extra text):
{{
  "winner": "<brand name that is winning overall>",
  "winner_reason": "<2-3 sentence explanation of why this brand is winning>",
  "biggest_loser": "<brand with the most concerning competitive position>",
  "loser_reason": "<1-2 sentence explanation>",
  "agent_insights": [
    "<non-obvious insight 1 — something a decision-maker wouldn't see from raw numbers>",
    "<non-obvious insight 2>",
    "<non-obvious insight 3>",
    "<non-obvious insight 4>",
    "<non-obvious insight 5>"
  ],
  "market_overview": "<2-3 sentence overview of the competitive landscape>",
  "price_vs_sentiment_note": "<1 sentence about the relationship between price and sentiment across brands>"
}}"""


def generate_competitive_narrative(brand_metrics: list[dict]) -> dict:
    """
    Call GPT to produce the competitive intelligence narrative.
    Falls back to a rule-based version if LLM fails.
    """
    prompt = build_competitive_summary_prompt(brand_metrics)

    try:
        response = client.chat.completions.create(
            model=LLM_MODEL,
            max_tokens=800,
            temperature=0.3,
            messages=[
                {"role": "system", "content": "Return only valid JSON. No markdown."},
                {"role": "user", "content": prompt},
            ],
        )
        raw = response.choices[0].message.content.strip()
        raw = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        return json.loads(raw)

    except Exception as e:
        print(f"[competitive_agent] Narrative generation failed: {e}")
        # Rule-based fallback: winner is brand with best combined rating + sentiment
        winner = max(brand_metrics, key=lambda x: x["avg_rating"] * 0.5 + x["sentiment_score"] * 0.5)
        return {
            "winner": winner["brand"],
            "winner_reason": f"{winner['brand']} leads on combined rating and sentiment scores.",
            "biggest_loser": "N/A",
            "loser_reason": "Data insufficient for loser determination.",
            "agent_insights": [
                "Higher discount brands don't always win on sentiment.",
                "Premium pricing correlates weakly with review satisfaction in this category.",
                "Zipper quality is a recurring complaint across all brands.",
                "Review volume varies significantly — high ratings on few reviews may be unreliable.",
                "Mid-range brands offer the strongest value-for-money in this dataset.",
            ],
            "market_overview": "The Indian luggage market shows competitive pricing with differentiation mainly on durability perception.",
            "price_vs_sentiment_note": "Price and sentiment show a non-linear relationship — mid-range brands often outperform premium ones on sentiment.",
            "fallback": True,
        }


# ── Overview stats ─────────────────────────────────────────────────────────

def build_overview(brand_metrics: list[dict]) -> dict:
    """
    Build the top-level dashboard overview numbers.
    These power the stat cards in the Overview view.
    """
    total_products = sum(b["product_count"] for b in brand_metrics)
    total_reviews = sum(b["total_reviews"] for b in brand_metrics)
    avg_sentiment = round(mean(b["sentiment_score"] for b in brand_metrics), 3)
    avg_price_all = round(mean(b["avg_price"] for b in brand_metrics if b["avg_price"]), 0)
    avg_rating_all = round(mean(b["avg_rating"] for b in brand_metrics if b["avg_rating"]), 2)
    avg_discount_all = round(mean(b["avg_discount_pct"] for b in brand_metrics if b["avg_discount_pct"]), 1)

    return {
        "brands_tracked": len(brand_metrics),
        "total_products": total_products,
        "total_reviews": total_reviews,
        "avg_sentiment": avg_sentiment,
        "avg_price": avg_price_all,
        "avg_rating": avg_rating_all,
        "avg_discount_pct": avg_discount_all,
    }


# ── Main orchestration ─────────────────────────────────────────────────────

def run_competitive_agent(brands: list[str] | None = None):
    """
    Load all processed brand insight files, compute metrics,
    generate narrative, and write the final competitive_summary.json.
    """
    brands = brands or TARGET_BRANDS
    brand_metrics_list = []

    for brand in brands:
        insights_path = PROCESSED_DIR / f"{brand.lower().replace(' ', '_')}_insights.json"
        brand_data = load_json(insights_path)

        if not brand_data:
            print(f"[competitive_agent] Missing insights for {brand}, skipping")
            continue

        metrics = compute_brand_metrics(brand_data)
        brand_metrics_list.append(metrics)
        print(f"[competitive_agent] ✓ Metrics computed for {brand}")

    if not brand_metrics_list:
        print("[competitive_agent] No brand data found. Run scraper + review agent first.")
        return

    # Add rank fields
    brand_metrics_list = rank_brands(brand_metrics_list)

    # Generate LLM narrative
    print("[competitive_agent] Generating competitive narrative...")
    narrative = generate_competitive_narrative(brand_metrics_list)

    # Build final output
    output = {
        "generated_at": timestamp(),
        "overview": build_overview(brand_metrics_list),
        "brands": brand_metrics_list,
        "competitive_narrative": narrative,
    }

    out_path = PROCESSED_DIR / "competitive_summary.json"
    save_json(output, out_path)
    print(f"\n[competitive_agent] ✓ Competitive summary saved → {out_path}")


# ── CLI entry point ────────────────────────────────────────────────────────

if __name__ == "__main__":
    brands_arg = sys.argv[1:] if len(sys.argv) > 1 else None
    run_competitive_agent(brands_arg)